# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c33c7798ac3172186e88a37341712a141a4972e8bf2e7bde2a7100bcf1a022e0fb1f5034a36ef8a0005edbf9ae985cd0905474124f64f246f4a4832592be4ce

test:
  secret_key_base: 070fab402d7d7f06f8396a8dd4d188295dfd87e0c7cc5e958437a1853ce6862814adbaf79510224d8aa8dd13db7fe0af237fc39205209af12d53e435294c62ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
